export const FETCH_PRICE_REQUEST = "FETCH_PRICE_REQUEST";
export const FETCH_PRICE_SUCCESS = "FETCH_PRICE_SUCCESS";
export const FETCH_PRICE_FAIL = "FETCH_PRICE_FAIL";

export const ADD_CURRENT_PRICE = "ADD_CURRENT_PRICE";
export const REMOVE_CURRENT_PRICE = "REMOVE_CURRENT_PRICE";

export const ADD_SAVED_PRICE = "ADD_SAVED_PRICE";
export const REMOVE_SAVED_PRICE = "REMOVE_SAVED_PRICE";
